### PR TITLE
Pass PAT token and authentication type for TFS images. Fixes #10

### LINKED ISSUE #10: Authentication issue
We just install TFS2017 on premise version 15.105.25910.0.

I'm trying to run an agent to a container by running the following command:

docker run -e TFS_HOST=tfs.mycompany.com -e TFS_URL=https://tfs.mycompany.com -e VSTS_TOKEN=************************** -e VSTS_AGENT=%hostname% -e VSTS_WORK=_work -e VSTS_POOL=docker -it microsoft/vsts-agent:ubuntu-16.04-tfs-2017

And I'm getting this output:

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /vsts/agent/externals/tee/license.html

>> Connect:

Invalid configuration provided for username. Terminating unattended configuration.

I tried also running an agent from a container with an account created on VS online, and it works fine:

docker run -e VSTS_ACCOUNT=enformat -e VSTS_TOKEN=***************************** -e VSTS_POOL=docker -it microsoft/vsts-agent:ubuntu-16.04

Is there any problem with start.sh script ?

Do we need to configure custom authentication on our servers (anonymous authentication is enabled) ? Right now we've got agents installed on premise and they are working fine.

### PR DESCRIPTION
**Pull request by stffabi**
fixes #10

### CODE REVIEW

**Comment by stepro** [comment]
Simple enough; thanks!

**Comment by stepro** [comment]
Building updated images; will report back when the Docker Hub repository has been updated.

**Comment by stepro** [comment]
The Docker Hub images have been updated.

**Comment by stffabi** [comment]
@stepro  Great, thanks.

**Pull request merged**
