### PR TITLE
adding conda to path

### PR DESCRIPTION
**Pull request by dparkar**
#127 #97

### CODE REVIEW

**Comment by brcrista** [comment]
This was meant to push build pipelines through the Conda Environment task to access Conda.  If there is functionality missing we should consider adding it through the task first

**Comment by dakale** [comment]
Im actually not opposed to this. I would expect users to be able to use conda via tasks, or manually via cli if they choose. Adding this to the path doesnt break any existing functionality, although Im a little worried about setting a precedent that tools can be expected in PATH, and I really dont want some to be there and some not

**Comment by brcrista** [comment]
@dakale this would also replace the Python and Pip currently in PATH

**Comment by dakale** [comment]
Hmm, based on that I think I agree. I wasn't aware of what conda actually brought, and I don't want to take a dependency on the ordering of PATH items. 

@dparkar Going forward please use the Conda Environment task in your build as recommended by @brcrista, or link the binaries you need into place

**Pull request closed without merging**
