### PR TITLE
1709 image and docker support

### PR DESCRIPTION
**Pull request by riezebosch**
Just copied the contents and modified the FROM.
Created a docker image installing the docker-cli and docker-compose.

Published the results [here](https://hub.docker.com/r/mriezebosch/vsts-agent/).

### CODE REVIEW

**Comment by olljanat** [comment]
@riezebosch 1803 is already released so probably it would be good idea migrate to that one?

**Comment by riezebosch** [comment]
@olljanat I lost my faith a little

**Comment by dakale** [comment]
How does this compare with #91 ? I am not very familiar with the versioning/tags for windows containers

**Comment by riezebosch** [comment]
@dakale Looks like what I've done manually can be done with the `Update.ps` from that PR.

**Pull request closed without merging**
