### PR TITLE
Include missing TZDATA for ubuntu:16.04 based images.

### PR DESCRIPTION
**Pull request by hardcorehead87**
The ubuntu:16.04 upstream image doesn't include TZDATA anymore for space-saving **([Github issue](https://github.com/docker-library/official-images/issues/2863#issuecomment-294607003))**. This however is required for TimeZoneInfo to work. Added TZDATA to the apt-get install list to reinclude the missing TZDATA for all ubuntu:16.04 based images.

### CODE REVIEW

**Comment by stepro** [comment]
To make this update, you should change the ubuntu/derived/standard/Dockerfile.template file and then run the update.sh shell script to propagate the change across all instances of the template. I'll accept the change after this and run another build/push of the images. Thanks!

**Comment by hardcorehead87** [comment]
I've made the requested changes.

**Comment by stepro** [comment]
The dotnet SDK is only in the standard images, so these are the only ones that are updated. I'll merge the commit and do another build/push of images.

**Comment by stepro** [comment]
The images have been updated.

**Pull request merged**
