### PR TITLE
Add libs to each PHP version. Add XSLT tools. Add svn capability.

### PR DESCRIPTION
**Pull request by DavidStaheli**
This addresses most of #115.  @madhancock, can you please look over the newly-included PHP modules?

### CODE REVIEW

**Comment by madhancock** [comment]
@DavidStaheli Builds and runs as expected. Module outputs all look good and composer is operating correctly. Thanks.

**Comment by DavidStaheli** [comment]
Wow, thanks a lot for trying this @madhancock.  It is a huge help.

**Comment by dakale** [comment]
LGTM. (Stephen wont be maintaining this repo much if at all going forward)

**Comment by DavidStaheli** [comment]
Thanks @dakale!

**Pull request merged**
